// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvVVrWaU7rER3rxek5lUWicSzt_oPfmh4',
    appId: '1:550892437055:web:c675e174096abdc854c28a',
    messagingSenderId: '550892437055',
    projectId: 'kioskplus-e45ce',
    authDomain: 'kioskplus-e45ce.firebaseapp.com',
    storageBucket: 'kioskplus-e45ce.appspot.com',
    measurementId: 'G-43X1085G4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7gcSq3fK83Pt6rfaKGyrEgcKN6SA5IaY',
    appId: '1:550892437055:android:21ef156ebe2b81f054c28a',
    messagingSenderId: '550892437055',
    projectId: 'kioskplus-e45ce',
    storageBucket: 'kioskplus-e45ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2TXY-kKZGmWIBQMDj_Rk9HmmYQIoq7u4',
    appId: '1:550892437055:ios:f027a7a878a5fddf54c28a',
    messagingSenderId: '550892437055',
    projectId: 'kioskplus-e45ce',
    storageBucket: 'kioskplus-e45ce.appspot.com',
    iosClientId: '550892437055-4co47om16a6uqn23hk2cv64va63dqu1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.kioskplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2TXY-kKZGmWIBQMDj_Rk9HmmYQIoq7u4',
    appId: '1:550892437055:ios:f027a7a878a5fddf54c28a',
    messagingSenderId: '550892437055',
    projectId: 'kioskplus-e45ce',
    storageBucket: 'kioskplus-e45ce.appspot.com',
    iosClientId: '550892437055-4co47om16a6uqn23hk2cv64va63dqu1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.kioskplus',
  );
}
